export const lmsData = {
  courses: [
    {
      id: 1,
      title: 'Artificial Intelligence & Machine Learning Engineering',
      skills: [
        'Python',
        'TensorFlow',
        'PyTorch',
        'Neural Networks',
        'NLP',
        'Generative AI',
      ],
      duration_weeks: 24,
      price_inr: 65000,
      hiring_potential: 'Very High',
      analytics: {
        total_revenue: 2600000,
        this_month_revenue: 260000,
        total_enrollments: 400,
        this_month_enrollments: 40,
        total_completions: 320,
        this_month_completions: 28,
      },
    },
    {
      id: 2,
      title: 'Full-Stack Web Development (MERN / MEAN / Django)',
      skills: [
        'React',
        'Angular',
        'Node.js',
        'Express',
        'MongoDB',
        'PostgreSQL',
        'Django',
      ],
      duration_weeks: 24,
      price_inr: 60000,
      hiring_potential: 'Very High',
      analytics: {
        total_revenue: 4800000,
        this_month_revenue: 600000,
        total_enrollments: 800,
        this_month_enrollments: 100,
        total_completions: 640,
        this_month_completions: 85,
      },
    },
    {
      id: 3,
      title: 'Cloud Computing & DevOps Engineering',
      skills: [
        'AWS',
        'Azure',
        'GCP',
        'Docker',
        'Kubernetes',
        'Terraform',
        'CI/CD',
      ],
      duration_weeks: 24,
      price_inr: 65000,
      hiring_potential: 'Very High',
      analytics: {
        total_revenue: 3250000,
        this_month_revenue: 390000,
        total_enrollments: 500,
        this_month_enrollments: 60,
        total_completions: 420,
        this_month_completions: 50,
      },
    },
    {
      id: 4,
      title: 'Cybersecurity & Ethical Hacking',
      skills: [
        'Penetration Testing',
        'Network Security',
        'Cloud Security',
        'OWASP',
        'Encryption',
      ],
      duration_weeks: 12,
      price_inr: 35000,
      hiring_potential: 'Very High',
      analytics: {
        total_revenue: 2100000,
        this_month_revenue: 315000,
        total_enrollments: 600,
        this_month_enrollments: 90,
        total_completions: 500,
        this_month_completions: 70,
      },
    },
    {
      id: 5,
      title: 'Data Science & Analytics',
      skills: [
        'Python',
        'R',
        'SQL',
        'Pandas',
        'Machine Learning',
        'Tableau',
        'Power BI',
      ],
      duration_weeks: 24,
      price_inr: 60000,
      hiring_potential: 'High',
      analytics: {
        total_revenue: 3600000,
        this_month_revenue: 480000,
        total_enrollments: 600,
        this_month_enrollments: 80,
        total_completions: 520,
        this_month_completions: 65,
      },
    },
    {
      id: 6,
      title: 'Big Data Engineering',
      skills: ['Hadoop', 'Spark', 'Kafka', 'NoSQL', 'ETL Pipelines'],
      duration_weeks: 24,
      price_inr: 55000,
      hiring_potential: 'High',
      analytics: {
        total_revenue: 1925000,
        this_month_revenue: 275000,
        total_enrollments: 350,
        this_month_enrollments: 50,
        total_completions: 280,
        this_month_completions: 40,
      },
    },
    {
      id: 7,
      title: 'Blockchain & Web3 Development',
      skills: ['Ethereum', 'Solidity', 'Smart Contracts', 'DApps'],
      duration_weeks: 12,
      price_inr: 40000,
      hiring_potential: 'Medium-High',
      analytics: {
        total_revenue: 1200000,
        this_month_revenue: 200000,
        total_enrollments: 300,
        this_month_enrollments: 50,
        total_completions: 240,
        this_month_completions: 40,
      },
    },
    {
      id: 8,
      title: 'Internet of Things (IoT) & Edge Computing',
      skills: ['Arduino', 'Raspberry Pi', 'Embedded Systems', 'AIoT'],
      duration_weeks: 12,
      price_inr: 35000,
      hiring_potential: 'Medium-High',
      analytics: {
        total_revenue: 1050000,
        this_month_revenue: 140000,
        total_enrollments: 300,
        this_month_enrollments: 40,
        total_completions: 220,
        this_month_completions: 35,
      },
    },
    {
      id: 9,
      title: 'AI-Integrated UI/UX / Product Engineering',
      skills: [
        'Figma',
        'Adobe XD',
        'AI Tools',
        'A/B Testing',
        'Design Thinking',
      ],
      duration_weeks: 6,
      price_inr: 20000,
      hiring_potential: 'Medium',
      analytics: {
        total_revenue: 800000,
        this_month_revenue: 120000,
        total_enrollments: 400,
        this_month_enrollments: 60,
        total_completions: 300,
        this_month_completions: 50,
      },
    },
    {
      id: 10,
      title: 'Full Stack + AI (Full-Stack AI Developer)',
      skills: ['React', 'Node.js', 'AI/ML Integration', 'LLMs'],
      duration_weeks: 24,
      price_inr: 65000,
      hiring_potential: 'High',
      analytics: {
        total_revenue: 2600000,
        this_month_revenue: 325000,
        total_enrollments: 400,
        this_month_enrollments: 50,
        total_completions: 300,
        this_month_completions: 42,
      },
    },
    {
      id: 11,
      title: 'AI-Assisted QA & Testing Engineering',
      skills: ['Selenium', 'Cypress', 'Playwright', 'AI in Test Automation'],
      duration_weeks: 12,
      price_inr: 30000,
      hiring_potential: 'Medium-High',
      analytics: {
        total_revenue: 900000,
        this_month_revenue: 120000,
        total_enrollments: 300,
        this_month_enrollments: 40,
        total_completions: 240,
        this_month_completions: 35,
      },
    },
    {
      id: 12,
      title: 'AI Literacy & Generative AI',
      skills: [
        'Prompt Engineering',
        'ChatGPT APIs',
        'LangChain',
        'RAG Applications',
      ],
      duration_weeks: 6,
      price_inr: 25000,
      hiring_potential: 'Very High',
      analytics: {
        total_revenue: 1250000,
        this_month_revenue: 225000,
        total_enrollments: 500,
        this_month_enrollments: 90,
        total_completions: 400,
        this_month_completions: 70,
      },
    },
    {
      id: 13,
      title: 'Quantum Computing Foundations',
      skills: [
        'Quantum Algorithms',
        'Qiskit',
        'Quantum Circuits',
        'Quantum Theory Basics',
      ],
      duration_weeks: 8,
      price_inr: 20000,
      hiring_potential: 'Emerging',
      analytics: {
        total_revenue: 400000,
        this_month_revenue: 80000,
        total_enrollments: 200,
        this_month_enrollments: 40,
        total_completions: 150,
        this_month_completions: 30,
      },
    },
    {
      id: 14,
      title: 'Sustainability-Informed Software Engineering',
      skills: [
        'Green Software Practices',
        'System Thinking',
        'Ethical AI',
        'Sustainable Design',
      ],
      duration_weeks: 10,
      price_inr: 18000,
      hiring_potential: 'Emerging',
      analytics: {
        total_revenue: 360000,
        this_month_revenue: 72000,
        total_enrollments: 200,
        this_month_enrollments: 40,
        total_completions: 150,
        this_month_completions: 25,
      },
    },
    {
      id: 15,
      title: 'Human-Centered Skills: Design Thinking & Soft Skills for Tech',
      skills: [
        'Collaboration',
        'Ethics',
        'Empathy',
        'Adaptability',
        'Problem-Solving',
      ],
      duration_weeks: 8,
      price_inr: 15000,
      hiring_potential: 'High (Complementary)',
      analytics: {
        total_revenue: 450000,
        this_month_revenue: 90000,
        total_enrollments: 300,
        this_month_enrollments: 60,
        total_completions: 250,
        this_month_completions: 40,
      },
    },
  ],
  assessments: [
    {
      assessment_name: 'Frontend Fundamentals Test',
      course: 'Full-Stack Web Development',
      duration_minutes: 45,
      total_revenue: 180000,
      this_month_revenue: 25000,
      total_attempts: 1200,
      this_month_attempts: 150,
      total_passes: 850,
      this_month_passes: 110,
      student_usage: 700,
      companies_usage: 500,
    },
    {
      assessment_name: 'Backend APIs & Databases Test',
      course: 'Full-Stack Web Development',
      duration_minutes: 50,
      total_revenue: 200000,
      this_month_revenue: 30000,
      total_attempts: 1300,
      this_month_attempts: 180,
      total_passes: 900,
      this_month_passes: 130,
      student_usage: 800,
      companies_usage: 500,
    },
    {
      assessment_name: 'Full-Stack Project Simulation',
      course: 'Full-Stack Web Development',
      duration_minutes: 60,
      total_revenue: 220000,
      this_month_revenue: 35000,
      total_attempts: 1250,
      this_month_attempts: 170,
      total_passes: 870,
      this_month_passes: 120,
      student_usage: 750,
      companies_usage: 500,
    },
    {
      assessment_name: 'Deployment & CI/CD Test',
      course: 'Full-Stack Web Development',
      duration_minutes: 45,
      total_revenue: 160000,
      this_month_revenue: 20000,
      total_attempts: 1100,
      this_month_attempts: 140,
      total_passes: 800,
      this_month_passes: 100,
      student_usage: 700,
      companies_usage: 400,
    },
    {
      assessment_name: 'Supervised Learning Test',
      course: 'Data Science & Machine Learning',
      duration_minutes: 50,
      total_revenue: 210000,
      this_month_revenue: 28000,
      total_attempts: 1350,
      this_month_attempts: 160,
      total_passes: 930,
      this_month_passes: 120,
      student_usage: 800,
      companies_usage: 550,
    },
    {
      assessment_name: 'Unsupervised Learning Test',
      course: 'Data Science & Machine Learning',
      duration_minutes: 45,
      total_revenue: 190000,
      this_month_revenue: 25000,
      total_attempts: 1250,
      this_month_attempts: 150,
      total_passes: 870,
      this_month_passes: 110,
      student_usage: 750,
      companies_usage: 500,
    },
    {
      assessment_name: 'Deep Learning & Neural Networks Test',
      course: 'Data Science & Machine Learning',
      duration_minutes: 60,
      total_revenue: 230000,
      this_month_revenue: 35000,
      total_attempts: 1400,
      this_month_attempts: 180,
      total_passes: 1000,
      this_month_passes: 130,
      student_usage: 800,
      companies_usage: 600,
    },
    {
      assessment_name: 'Data Science Project Simulation',
      course: 'Data Science & Machine Learning',
      duration_minutes: 60,
      total_revenue: 250000,
      this_month_revenue: 40000,
      total_attempts: 1450,
      this_month_attempts: 190,
      total_passes: 1050,
      this_month_passes: 140,
      student_usage: 850,
      companies_usage: 600,
    },
    {
      assessment_name: 'React Basics Test',
      course: 'Frontend Development (React + Next.js)',
      duration_minutes: 40,
      total_revenue: 150000,
      this_month_revenue: 20000,
      total_attempts: 1000,
      this_month_attempts: 130,
      total_passes: 720,
      this_month_passes: 95,
      student_usage: 600,
      companies_usage: 400,
    },
    {
      assessment_name: 'Next.js Advanced Test',
      course: 'Frontend Development (React + Next.js)',
      duration_minutes: 50,
      total_revenue: 170000,
      this_month_revenue: 25000,
      total_attempts: 1100,
      this_month_attempts: 150,
      total_passes: 800,
      this_month_passes: 115,
      student_usage: 650,
      companies_usage: 450,
    },
    {
      assessment_name: 'Frontend Deployment Simulation',
      course: 'Frontend Development (React + Next.js)',
      duration_minutes: 45,
      total_revenue: 160000,
      this_month_revenue: 22000,
      total_attempts: 1050,
      this_month_attempts: 140,
      total_passes: 770,
      this_month_passes: 100,
      student_usage: 620,
      companies_usage: 430,
    },
    {
      assessment_name: 'Python Basics Test',
      course: 'Python Programming & Automation',
      duration_minutes: 40,
      total_revenue: 140000,
      this_month_revenue: 18000,
      total_attempts: 950,
      this_month_attempts: 120,
      total_passes: 700,
      this_month_passes: 95,
      student_usage: 600,
      companies_usage: 350,
    },
    {
      assessment_name: 'Automation Scripting Test',
      course: 'Python Programming & Automation',
      duration_minutes: 50,
      total_revenue: 150000,
      this_month_revenue: 20000,
      total_attempts: 1000,
      this_month_attempts: 130,
      total_passes: 730,
      this_month_passes: 100,
      student_usage: 650,
      companies_usage: 350,
    },
    {
      assessment_name: 'Python Project Simulation',
      course: 'Python Programming & Automation',
      duration_minutes: 45,
      total_revenue: 160000,
      this_month_revenue: 22000,
      total_attempts: 1050,
      this_month_attempts: 140,
      total_passes: 760,
      this_month_passes: 105,
      student_usage: 670,
      companies_usage: 380,
    },
    {
      assessment_name: 'Core Java Test',
      course: 'Java Backend Development (Spring Boot)',
      duration_minutes: 45,
      total_revenue: 170000,
      this_month_revenue: 24000,
      total_attempts: 1100,
      this_month_attempts: 145,
      total_passes: 800,
      this_month_passes: 110,
      student_usage: 650,
      companies_usage: 450,
    },
    {
      assessment_name: 'Spring Boot APIs Test',
      course: 'Java Backend Development (Spring Boot)',
      duration_minutes: 50,
      total_revenue: 180000,
      this_month_revenue: 26000,
      total_attempts: 1150,
      this_month_attempts: 150,
      total_passes: 830,
      this_month_passes: 115,
      student_usage: 670,
      companies_usage: 480,
    },
    {
      assessment_name: 'Java Project Simulation',
      course: 'Java Backend Development (Spring Boot)',
      duration_minutes: 60,
      total_revenue: 200000,
      this_month_revenue: 30000,
      total_attempts: 1200,
      this_month_attempts: 160,
      total_passes: 880,
      this_month_passes: 125,
      student_usage: 700,
      companies_usage: 500,
    },
    {
      assessment_name: 'Cloud Basics Test',
      course: 'Cloud Computing with AWS & DevOps',
      duration_minutes: 45,
      total_revenue: 200000,
      this_month_revenue: 28000,
      total_attempts: 1300,
      this_month_attempts: 170,
      total_passes: 950,
      this_month_passes: 125,
      student_usage: 850,
      companies_usage: 450,
    },
    {
      assessment_name: 'DevOps CI/CD Test',
      course: 'Cloud Computing with AWS & DevOps',
      duration_minutes: 50,
      total_revenue: 220000,
      this_month_revenue: 32000,
      total_attempts: 1350,
      this_month_attempts: 180,
      total_passes: 1000,
      this_month_passes: 130,
      student_usage: 900,
      companies_usage: 450,
    },
    {
      assessment_name: 'Cloud Project Simulation',
      course: 'Cloud Computing with AWS & DevOps',
      duration_minutes: 60,
      total_revenue: 240000,
      this_month_revenue: 35000,
      total_attempts: 1400,
      this_month_attempts: 190,
      total_passes: 1050,
      this_month_passes: 140,
      student_usage: 900,
      companies_usage: 500,
    },
    {
      assessment_name: 'Data Wrangling & Cleaning Test',
      course: 'Data Analytics with Power BI & SQL',
      duration_minutes: 40,
      total_revenue: 150000,
      this_month_revenue: 20000,
      total_attempts: 1000,
      this_month_attempts: 130,
      total_passes: 740,
      this_month_passes: 100,
      student_usage: 600,
      companies_usage: 400,
    },
    {
      assessment_name: 'SQL Querying Test',
      course: 'Data Analytics with Power BI & SQL',
      duration_minutes: 50,
      total_revenue: 160000,
      this_month_revenue: 22000,
      total_attempts: 1050,
      this_month_attempts: 140,
      total_passes: 770,
      this_month_passes: 105,
      student_usage: 630,
      companies_usage: 420,
    },
    {
      assessment_name: 'Power BI Dashboard Simulation',
      course: 'Data Analytics with Power BI & SQL',
      duration_minutes: 60,
      total_revenue: 180000,
      this_month_revenue: 25000,
      total_attempts: 1100,
      this_month_attempts: 150,
      total_passes: 800,
      this_month_passes: 110,
      student_usage: 650,
      companies_usage: 450,
    },
    {
      assessment_name: 'Cybersecurity Fundamentals Test',
      course: 'Cybersecurity & Ethical Hacking',
      duration_minutes: 45,
      total_revenue: 170000,
      this_month_revenue: 23000,
      total_attempts: 1150,
      this_month_attempts: 150,
      total_passes: 820,
      this_month_passes: 115,
      student_usage: 600,
      companies_usage: 550,
    },
    {
      assessment_name: 'Penetration Testing Simulation',
      course: 'Cybersecurity & Ethical Hacking',
      duration_minutes: 60,
      total_revenue: 190000,
      this_month_revenue: 27000,
      total_attempts: 1200,
      this_month_attempts: 160,
      total_passes: 860,
      this_month_passes: 120,
      student_usage: 750,
      companies_usage: 450,
    },
    {
      assessment_name: 'Cybersecurity Project Test',
      course: 'Cybersecurity & Ethical Hacking',
      duration_minutes: 60,
      total_revenue: 200000,
      this_month_revenue: 30000,
      total_attempts: 1250,
      this_month_attempts: 170,
      total_passes: 890,
      this_month_passes: 130,
      student_usage: 800,
      companies_usage: 450,
    },
    {
      assessment_name: 'Mobile App Basics Test',
      course: 'Mobile App Development (Flutter & React Native)',
      duration_minutes: 40,
      total_revenue: 160000,
      this_month_revenue: 22000,
      total_attempts: 1050,
      this_month_attempts: 140,
      total_passes: 770,
      this_month_passes: 100,
      student_usage: 600,
      companies_usage: 450,
    },
    {
      assessment_name: 'Cross-Platform Test',
      course: 'Mobile App Development (Flutter & React Native)',
      duration_minutes: 50,
      total_revenue: 170000,
      this_month_revenue: 24000,
      total_attempts: 1100,
      this_month_attempts: 150,
      total_passes: 800,
      this_month_passes: 115,
      student_usage: 650,
      companies_usage: 450,
    },
    {
      assessment_name: 'Mobile App Deployment Simulation',
      course: 'Mobile App Development (Flutter & React Native)',
      duration_minutes: 60,
      total_revenue: 180000,
      this_month_revenue: 26000,
      total_attempts: 1150,
      this_month_attempts: 160,
      total_passes: 820,
      this_month_passes: 120,
      student_usage: 700,
      companies_usage: 450,
    },
    {
      assessment_name: 'AI Prompt Engineering Test',
      course: 'Artificial Intelligence (AI) Engineering',
      duration_minutes: 45,
      total_revenue: 200000,
      this_month_revenue: 28000,
      total_attempts: 1300,
      this_month_attempts: 170,
      total_passes: 950,
      this_month_passes: 130,
      student_usage: 800,
      companies_usage: 500,
    },
    {
      assessment_name: 'AI Model Deployment Test',
      course: 'Artificial Intelligence (AI) Engineering',
      duration_minutes: 60,
      total_revenue: 220000,
      this_month_revenue: 32000,
      total_attempts: 1350,
      this_month_attempts: 180,
      total_passes: 1000,
      this_month_passes: 140,
      student_usage: 850,
      companies_usage: 500,
    },
    {
      assessment_name: 'AI Use Case Project Simulation',
      course: 'Artificial Intelligence (AI) Engineering',
      duration_minutes: 60,
      total_revenue: 240000,
      this_month_revenue: 35000,
      total_attempts: 1400,
      this_month_attempts: 190,
      total_passes: 1050,
      this_month_passes: 145,
      student_usage: 900,
      companies_usage: 500,
    },
    {
      assessment_name: 'Blockchain Basics Test',
      course: 'Blockchain Development',
      duration_minutes: 45,
      total_revenue: 170000,
      this_month_revenue: 23000,
      total_attempts: 1150,
      this_month_attempts: 150,
      total_passes: 820,
      this_month_passes: 115,
      student_usage: 850,
      companies_usage: 300,
    },
    {
      assessment_name: 'Smart Contracts Test',
      course: 'Blockchain Development',
      duration_minutes: 50,
      total_revenue: 180000,
      this_month_revenue: 26000,
      total_attempts: 1200,
      this_month_attempts: 160,
      total_passes: 850,
      this_month_passes: 120,
      student_usage: 870,
      companies_usage: 330,
    },
    {
      assessment_name: 'Blockchain Project Simulation',
      course: 'Blockchain Development',
      duration_minutes: 60,
      total_revenue: 190000,
      this_month_revenue: 28000,
      total_attempts: 1250,
      this_month_attempts: 170,
      total_passes: 880,
      this_month_passes: 125,
      student_usage: 900,
      companies_usage: 350,
    },
    {
      assessment_name: 'UI/UX Basics Test',
      course: 'UI/UX Design & Prototyping',
      duration_minutes: 40,
      total_revenue: 140000,
      this_month_revenue: 19000,
      total_attempts: 900,
      this_month_attempts: 120,
      total_passes: 650,
      this_month_passes: 95,
      student_usage: 600,
      companies_usage: 300,
    },
    {
      assessment_name: 'Wireframing & Prototyping Test',
      course: 'UI/UX Design & Prototyping',
      duration_minutes: 50,
      total_revenue: 150000,
      this_month_revenue: 21000,
      total_attempts: 950,
      this_month_attempts: 130,
      total_passes: 680,
      this_month_passes: 100,
      student_usage: 600,
      companies_usage: 350,
    },
    {
      assessment_name: 'UI/UX Project Simulation',
      course: 'UI/UX Design & Prototyping',
      duration_minutes: 60,
      total_revenue: 160000,
      this_month_revenue: 23000,
      total_attempts: 1000,
      this_month_attempts: 140,
      total_passes: 720,
      this_month_passes: 110,
      student_usage: 650,
      companies_usage: 350,
    },
    {
      assessment_name: 'IoT Fundamentals Test',
      course: 'Internet of Things (IoT) Development',
      duration_minutes: 45,
      total_revenue: 160000,
      this_month_revenue: 22000,
      total_attempts: 1050,
      this_month_attempts: 140,
      total_passes: 770,
      this_month_passes: 105,
      student_usage: 600,
      companies_usage: 450,
    },
    {
      assessment_name: 'Embedded Systems Test',
      course: 'Internet of Things (IoT) Development',
      duration_minutes: 50,
      total_revenue: 170000,
      this_month_revenue: 24000,
      total_attempts: 1100,
      this_month_attempts: 150,
      total_passes: 800,
      this_month_passes: 115,
      student_usage: 650,
      companies_usage: 450,
    },
    {
      assessment_name: 'IoT Project Simulation',
      course: 'Internet of Things (IoT) Development',
      duration_minutes: 60,
      total_revenue: 180000,
      this_month_revenue: 26000,
      total_attempts: 1150,
      this_month_attempts: 160,
      total_passes: 830,
      this_month_passes: 120,
      student_usage: 700,
      companies_usage: 450,
    },
    {
      assessment_name: 'NLP Basics Test',
      course: 'Natural Language Processing (NLP)',
      duration_minutes: 45,
      total_revenue: 180000,
      this_month_revenue: 25000,
      total_attempts: 1150,
      this_month_attempts: 150,
      total_passes: 830,
      this_month_passes: 115,
      student_usage: 700,
      companies_usage: 450,
    },
  ],
};
